server:
  port: 9093
spring:
  jackson:
    generator:
      write_numbers_as_strings: true
    time-zone: GMT+8
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ali:
  ossKey: LTAI5tGAQreYB1UJ8GSVkQvH
  ossSecret: JtlN9qR5jXrRKBi1EZvsx31cfpJ8lY
upload:
  path: E:\test
---
spring:
  datasource:
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fkx?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=GMT%2b8
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher